# Generated by Django 4.1.1 on 2022-12-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_registrationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='password',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='password_confirm',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
